version: '3.4'

services:
  quizzer.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=50000
      - ASPNETCORE_HTTPS_PORTS=50001
    ports:
      - "50000:50000"
      - "50001:50001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro